ds_topology:
  main_columns: [id, case_name, full_uc_text, full_ssts_text]
  hmi_subheaders:
    preconditions: preconditions
    main_scenario: main_scenario
    postconditions: postconditions
    alternative_scenario_a: other
    alternative_scenario_b: other
    alternative_scenario_c: other
    description: other
    goal: goal
    context: other
    scope: other
    actors: other
    requirements: other
    trigger: other
    alternative_scenarios: other
    alternative_scenario: other
    use_case_title: other
    alternative_scenario_a_a(turn_off_the_hotspot): other
    tigger: other
    components: other
    function_logic: other
    additional_info: other
    display: other
    notification: other
    use_case: other
    triggers: other
    requirenments: other
  targets: [Differences, Description, Complience Level]

target_dict:
  FC: 5
  LC: 4
  PC: 3
  NC: 2
  NA: 1

ds:
  sep: "|"
  encoding: utf-8

bert: bert-base-uncased
distance_metric: cosine